version: "3.9"
   
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks: 
      - dbnetwork
  
  redis:
    image: redis
    ports: 
      - 6379:6379


  web:
    build: .
    restart: always
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - redis
    links: 
      - db:db
    
    networks: 
      - dbnetwork
  

  celery:
    restart: always
    build:
      context: .
    command: celery -A task worker -l info
    depends_on:
      - db
      - redis
      - web
  
networks: 
  dbnetwork:
        driver: bridge 

volumes:
  db_volume:
    external: true
